### ISSUE TITLE
Version 1.3.0 do not authenticate with flickr

### ISSUE THREAD

**Issue by ceinmart** [mistic100/Flickr2Piwigo#11]
Hi, 
I've reinstalled the plugin using the piwigo admin interface. 
Its show is version 1.3.0.
When click at "login" button , then raise the error below .
What could be?
PHP version?

> Fatal error: Uncaught OAuth\Common\Http\Exception\TokenResponseException: file_get_contents(https://www.flickr.com/services/oauth/request_token): failed to open stream: no suitable wrapper could be found in /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:73 Stack trace: #0 /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/AbstractService.php(52): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), '', Array) #1 /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhpFlickr.php(718): OAuth\OAuth1\Service\AbstractService->requestRequestToken() #2 /home/imartins/public_html/fotos/plugins/flickr2piwigo/admin/import.php(60): Samwilson\PhpFlickr\PhpFlickr->getAuthUrl('read', 'https://fotos.i...') #3 /home/imartins/public_html/fotos/plugins/flickr2piwigo/admin.php(19): include('/home/imartins/...') #4 /home/imartins/public_html/f in /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php on line 73

Piwigo 2.9.2
Operating system: Linux
PHP: 7.0.27 (Show info) [2018-02-20 15:41:22]
MySQL: 5.6.36-cll-lve [2018-02-20 12:41:22]
Graphics Library: External ImageMagick 6.7.8-9

**Comment by samwilson** [comment]
This is most likely due to your PHP setup not having URL fopen wrappers enabled; see https://secure.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

I've switched PhpFlickr to use the Curl HTTP client, which should avoid this, and released 1.3.1. Can you try again?

**Comment by ceinmart** [comment]
Hi Sam, 
Works now!
But after login and authorize the access they back to piwigo at the page with "login" button, a float message says I'm logged at flickr , but I expected to see my albums... and if I click at Login button again, they redirect again to flickr page asking the autorization... and then back to piwigo again...

**Comment by samwilson** [comment]
hmm sounds wrong! I'll fix it tomorrow or so. but what happens if when you're redirected back and it says login again, you instead just click on the fl2pigo link again to reload the page? I'm thinking it might actually be working but not hamdling the redirect right.
--

**Comment by ceinmart** [comment]
I try again and I got same behave, but after back from the flickr autentication I forced a refresh at piwigo page and then appear two buttos : to list my albuns and import them. 
So ,just details , lol....
I will close this, ok
Thank you!!!

**Comment by samwilson** [comment]
Cool, thanks for confirming!

I'll fix it up, even though there's a workaround. Would be nice if it behaved correctly. :)

**Comment by samwilson** [comment]
Okay, updated and version 1.3.2 released.
