### ISSUE TITLE
Support Flickr's date granularities

### ISSUE THREAD

**Issue by samwilson** [mistic100/Flickr2Piwigo#14]
Flickr items have a date, and a "date granularity" which determines *how much* of the date is accurate.

Granularity | Format
-- | --
0 | Y-m-d H:i:s
4 | Y-m
6 | Y
8 | Circa Y

See https://www.flickr.com/services/api/misc.dates.html form more info.

I'm not really sure how Piwigo can support this, as we need to be able to modify the date inputs everywhere, and all the places that the date is displayed (including the calendar view, where we'd want to be able to list photos that e.g. only have a year or a month, and no day).

I think this could be a separate plugin, because it's something that would be useful even without any connection to Flickr. Could still use the same granularity identifiers though, for simplicity (they seem a reasonable design).

Alternatively, perhaps flickr2piwigo could just add keywords for these approximate dates? At least for now, so we don't through this information away.

**Comment by biffhero** [comment]
Maybe a tag called "flickr_date", which would show the value that flickr gives.  Would it make sense to have a tag called "flickr_granularity", too?

**Comment by samwilson** [comment]
You mean a sort of "machine tag" keyword? e.g. `flickr_date=c. 1930` rather than just `c. 1930`, and an accompanying `flickr_granularity=8`?

We could also add a keyword like `Approximate date` or something (where granularity is greater than 0), to make it easier to filter for all these.

**Comment by biffhero** [comment]
Yes, that's a good explanation of what I was trying to say, as I was hoping to make it easier to parse with a program.

**Comment by samwilson** [comment]
I think these would have to be optional extra things that the user could choose to import, wouldn't they?

E.g. the import screen (which currently lists checkboxes for: Photo name, Author, Keywords, Creation date, Post date, Description, Geolocalization, & Privacy level) would have an extra checkbox called "Keywords for approximate dates" that would create a:

* Date keyword (e.g. `c. 1933`, `March 2008`, or `1986`); and a
* Granularity keyword (one of: `Month`, `Year`, `Circa`)

It doesn't have to handle the case of 'exact', because that date is inserted to the core Piwigo date field. The documentation will have to mention that approximate dates will be imported as having an exact date and that this will likely not actually be correct. (For example, "c. 2006" is actually given as `2006-01-01 00:00:00` by Flickr, and that's what gets put in the Piwigo date field.)

**Comment by biffhero** [comment]
Thanks for the explanation.  I think that bringing in the "c. 2006" as 2006-01-01 00:00:00 is going to cause surprises for the' end users.  Maybe we can stave that off by a big fat warning message.  It's so sad, as 2006-01-01 00:00:00 is just as valid as 2006-12-31 23:59:59.

**Comment by samwilson** [comment]
I think we'll just have to have that big warning, and let people figure it out. Maybe one day Piwigo will support approximate dates! :)

At least it will help a bit to have every approximate-date photo tagged as such. I wonder if we should also add a `Approximate date` keyword as well, along with the other two?

**Comment by samwilson** [comment]
I have started work on this in #25.

**Comment by samwilson** [comment]
Done.
