### ISSUE TITLE
Add continuous integration tests

### ISSUE THREAD

**Issue by samwilson** [mistic100/Flickr2Piwigo#16]
We should add some continuous integration for coding standards etc.

I have started this, with adding Scrutinizer; see https://github.com/samwilson/Flickr2Piwigo/pull/1 where it's doing various tests: https://github.com/samwilson/Flickr2Piwigo/pull/1/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R15

The code quality is currently: [![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/samwilson/Flickr2Piwigo/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/samwilson/Flickr2Piwigo/?branch=master)

I think before it should go any further, however, the vendor directory should be removed from the repository. It seems like it will be easy to generate a distribution zip file for upload to piwigo.org, and if we do that we can selectively include only the bits of `vendor/`that are required and thus keep the download size as small as possible.

@mistic100 what do you think of Scrutinizer? It'd require a repo admin to activate it.

**Comment by samwilson** [comment]
Thanks @mistic100 :)

All set up now.

**Comment by mistic100** [comment]
I made you admin on Scrutinizer too
