### ISSUE TITLE
Import restricted and moderate photos as private, and add tags

### ISSUE THREAD

**Issue by samwilson** [mistic100/Flickr2Piwigo#17]
Requested in #12:

> Would it be possible to import and store the safety status of the photo from flickr, such as safe, moderate, or restricted?
> If this isn't possible or easy, would it be possible to import moderate and restricted photos as private, while importing the safe photos as public?

I don't think it's easy to store a new metadata key for the safety status, but certainly we should import them as private, and I think also add a keyword so it's easy to search for and modify them as required.

Does that sound okay?

**Comment by ElliotMcGucken** [comment]
Thanks Sam!  That would be great!

A unique keyword such as "f2p_safe" "f2p_moderate" and "f2p_restricted" would be great and easy to work with!

When might this be working?

Thank you!  Elliot

**Comment by samwilson** [comment]
Soon I hope! :-)

I think we can just have the 'moderate' and 'restricted' keywords, because 'safe' is assumed and the default. Does that work for you?

**Comment by ElliotMcGucken** [comment]
Yes!  That would be great!  Thanks! :)

**Comment by samwilson** [comment]
Done. Releasing 1.4.0 now.

**Comment by ElliotMcGucken** [comment]
Thanks Sam!

In order to install Flickr2Piwigo, I first typed: 
git clone -b import-all https://github.com/mistic100/Flickr2Piwigo.git

But that branch wasn't there.

So then I typed:
git clone https://github.com/mistic100/Flickr2Piwigo.git

Then. when I ran it from the browser, the **vendor** directory was missing, so I was getting errs that scripts/functions in the vendor directory could not be found .

So I copied the vendor directory from an older installation, and now it seems to be working.

Is this installation procedure OK?

What is the best/simplest way to install?

Thanks!

P.S. It seems to be running OK as I type this!

**Comment by samwilson** [comment]
Sorry, yes, I've changed the deployment process and not yet updated the documentation! You need to run `composer update --no-dev` in the flickr2piwigo directory after cloning the repository. Use the `master` branch, or any specific pull request's branch. Or download the zip from from http://piwigo.org/ext/extension_view.php?eid=612

**Comment by ElliotMcGucken** [comment]
Thanks Sam!  So is my current install OK?

I installed it like this today:

> 
> git clone https://github.com/mistic100/Flickr2Piwigo.git
> 
> Then. when I ran it from the browser, the vendor directory was missing, so I was getting errors that scripts/functions in the vendor directory could not be found .
> 
> So I copied the vendor directory from an older installation, and now it seems to be working.
> 
> Is this installation procedure OK?

Will it put the moderate and restricted photos in private directories?

Here are the log files for this install:
http://66.45.225.82/29pw/piwigo/_data/logs/

It seems to be running OK.  Will it put the moderate and restricted photos in private directories?

Thanks!

**Comment by ElliotMcGucken** [comment]
Dear Sam,

What should I do?  Should I start over again?

Is the current install OK?

Should I  run composer update --no-dev in the flickr2piwigo directory after cloning the repository.?

Should I download the zip from from http://piwigo.org/ext/extension_view.php?eid=612

I installed it like this today:

> 
> 
> git clone https://github.com/mistic100/Flickr2Piwigo.git
> 
> Then. when I ran it from the browser, the vendor directory was missing, so I was getting errors that scripts/functions in the vendor directory could not be found .
> 
> So I copied the vendor directory from an older installation, and now it seems to be working.
> 
> Is this installation procedure OK?

Will it put the moderate and restricted photos in private directories?

Here are the log files for this install:
http://66.45.225.82/29pw/piwigo/_data/logs/

It seems to be running OK. Will it put the moderate and restricted photos in private directories?

**Comment by samwilson** [comment]
Yeah, the old `vendor/` directory should be fine, for now. There will be updates to it though, in the future. For any production use, I'd recommend using the built-in Piwigo plugin updater.

And no, moderate and restricted photos will not be in any separate directory, but will get their own keywords so you can filter on them and modify them however you need to.

**Comment by samwilson** [comment]
It's only when testing new branches that you need to install it via Git.

**Comment by ElliotMcGucken** [comment]
Thanks Sam!

What are the keywords you are using for the moderate and restricted photos?

Also, are the moderate and restricted photos now imported with the status of "private," with their own keywords?

Thanks!

**Comment by samwilson** [comment]
The keywords are `Moderate` and `Restricted`. And no, the access control is set to the same as what is set on Flickr (i.e. friends, family, etc.) and not with keywords.

**Comment by ElliotMcGucken** [comment]
Thanks!  So will "Private" photos be imported as Private and hidden from view?

**Comment by samwilson** [comment]
Yes, they'll be 'admin' only.
