### ISSUE TITLE
Flickr2Piwigo only imports the first 500 images in a Flickr album

### ISSUE THREAD

**Issue by gmenzel** [mistic100/Flickr2Piwigo#21]
I notice that when I try to import an album with more than 500 images, only the first 500 images are imported. Is there a work-around for this limitation?

**Comment by samwilson** [comment]
This is a known bug, and is being tracked in #4. A fix should be coming soon.

**Comment by gmenzel** [comment]
Ah sorry I missed that. Thanks!
