### ISSUE TITLE
Only imported 528 of 3060

### ISSUE THREAD

**Issue by biffhero** [mistic100/Flickr2Piwigo#3]
Is there a rate limit imposed by Flickr?

**Comment by mistic100** [comment]
I think the limit is 500 on Flickr side.

**Comment by biffhero** [comment]
Yeah, I found that in a forum topic.  I was able to get 528.  I guess this could be called an enhancement request instead of a bug.

I'll get you an update to the documentation, that should help a bit with the initial confusion.
