### ISSUE TITLE
Error line 88

### ISSUE THREAD

**Issue by nedder77** [mistic100/Flickr2Piwigo#31]
×
ERROR
An error happened: 
Fatal error: Call to a member function debug() on null in /home/nedder77/plugins/flickr2piwigo/include/ws_functions.inc.php on line 88

This is line 88.

$logger->debug('Attempting to import Flickr photo '.$params['id'], FLICKR2PIWIGO);

**Comment by nedder77** [comment]
1.4.0 for This plugin, it's the one that is there when you do a search for Plugins via Piwigo's admin console.

Piwigo, I am on 2.7.4 because I can't get the new version to install correctly on my webhost, and that is the version they currently have up and running as part of an auto-install.

I will try updating the version of the plugin, I would have assumed the most recent version is what would have been coming up in the search.

**Comment by nedder77** [comment]
Same thing... line 89 now.

ERROR
An error happened: 
Fatal error: Call to a member function debug() on null in /home/nedder77/plugins/flickr2piwigo/include/ws_functions.inc.php on line 89

Also, there is no local/config/config.inc.php file there is a database.inc.php though.

**Comment by mistic100** [comment]
The Logger was added in Piwigo 2.8, this plugin cannot work on 2.7

**Comment by samwilson** [comment]
I've updated the version compatibility in the extension download.

@nedder77 it's recommended to update to the latest Piwigo if you can. What error are you getting? I'm sure we can figure out what's going wrong and get you up and running with 2.9.4! :-)

@mistic100 I thought the plugin downloader would warn against installing, based on what's specified in the extension page on piwigo.org, but perhaps it doesn't. Should I add in some better checks for version so it fails in a nicer way for older versions?

**Comment by mistic100** [comment]
All the versions you published are marked compatible 2.7 but 1.5.1 which is 2.9 only (???) and 1.5.2 which is 2.9 and 2.8

So I don't kwow when you added the logger but you can still edit the versions and remove 2.7 from the list

**Comment by mistic100** [comment]
It was add in 1.3.3 https://github.com/mistic100/Flickr2Piwigo/commit/552b79f97e4436fff9d55f7287cd0bd3b158f6cc

**Comment by mistic100** [comment]
And 1.4.0 is 2.9 and 2.7 but no 2.8 ? that's a mess :-)

**Comment by samwilson** [comment]
Erk, yes! I'm so sorry about this! :-( I've fixed it up. The last three releases are compatible only with 2.8 and later.

**Comment by samwilson** [comment]
Should probably have bumped it to 2.0.0 with the non-backwards compatible release, but I guess it's done now. Will take more care from now on.

**Comment by samwilson** [comment]
This should all be fine now, with new versions of Piwigo and the plugin.
