### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by flop25** [mistic100/Flickr2Piwigo#33]
Hi @mistic100 and @samwilson 
from https://twitter.com/hehark/status/1061007503624990720

 Warning:  Invalid argument supplied for foreach() in /home/sys/var/www/piwigo_master_29/plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhotosApi.php on line 77
 {"stat":"ok","result":"Photo \"\" imported"}

when importing

**Comment by samwilson** [comment]
This was fixed upstream in https://github.com/samwilson/phpflickr/commit/a47d613f7686cac32b49645756df4205b234236b but I thought had been released and included in Flickr2Piwigo. Perhaps not. I'm away from home just now; will check soon. Thanks for passing on the report!

**Comment by samwilson** [comment]
This issue was already fixed.

I've released 1.5.3 though, anyway, because there were some language updates to go out.
