### ISSUE TITLE
A question about flickr_cache (not really an issue)

### ISSUE THREAD

**Issue by kinmenRP** [mistic100/Flickr2Piwigo#35]
Hello. I've successfully imported my pictures fro Flickr, after some attempts. I would like to ask what's the folder flickr_cache for, and if it's possible to delete it. The reason is that I'm on a free host with limited inode and that folder is full of small files. Thank you.

**Comment by samwilson** [comment]
Yep, you can totally delete that directory. It holds the cache for Flickr API requests, in order to speed up things such as the album listing. If you delete it, it'll be recreated as required.

The fact that there's no auto-purging is a bug, though! Or at least a missing feature. :)

**Comment by samwilson** [comment]
Tracking the cache-purging as #36.

**Comment by kinmenRP** [comment]
Thank you very much
