### ISSUE TITLE
It works in background?

### ISSUE THREAD

**Issue by s-krawczyk** [mistic100/Flickr2Piwigo#44]
Does it work in background if I run it for 19k photos? Or browser has to be open all the time? What with the session of PHP?

**Comment by samwilson** [comment]
No, I'm afraid the browser window has to stay open. There is a plan to add a CLI tool, which could then be run via cron, but it's not done yet; it's being tracked in #13.

However, doing through the browser has worked fine for some people with up to many tens of thousands of images, so maybe give it a go and see what happens. If you restart the process, it'll not re-import the ones it's already done.
