### ISSUE TITLE
Half grey images imported - where to look for the cause?

### ISSUE THREAD

**Issue by Olli** [mistic100/Flickr2Piwigo#45]
I'd tried to import albums from flickr. The images get imported but some of them are half grey. 
I'd take look into the logfile and can't find any hint of the cause. I also tried this with a new install on a server where the script has way more RAM and can run longer. The results are the same. 
The grey images are different on different imports. Also often the first part of the image is not grey but shows parts of the original image. 
I can't figure out whether it is caused by my Piwigo installation or flickr.

Any comments?

**Comment by felixkrohn** [comment]
I'd almost certainly rule out a problem on flickr itself - sounds either like an error on transmission (which size do those pictures have?) or storage. If it's only on converted sizes (i.e. original-sized photo is ok) this would narrow it down to the conversion process - can you check this?

**Comment by Olli** [comment]
They are in original size .. around 6 to 10 MB.

**Comment by felixkrohn** [comment]
If there's nothing helpful in your webserver logs, try enabling debugging in piwigo and check $PIWIGO_INSTALL_DIR/piwigo/_data/logs/* for errors

**Comment by Olli** [comment]
You mean the $conf['log_level'] = 'DEBUG'; parameter?
Isn't it on debug by default?

**Comment by legrex** [comment]
I have exact the same problem on a piwigo-installation, with different flickr accounts. Nearly half of them are imported half or almost full grey. Without errors, they all got the "Success" popup. Also in Apache/PHP-Logfiles i see no error. 
Example image, as it's stored and shown in Piwigo:
![20190126225038-03bce91e](https://user-images.githubusercontent.com/1283867/51793243-824b0180-21bd-11e9-83b0-53cbda6ddd90.jpg)

**Comment by felixkrohn** [comment]
Do all broken files have exactly 500 KiB? Might be a php, memory or filesystem limit... did your logs in $PIWIGO_INSTALL_DIR/piwigo/_data/logs/* give anything?

**Comment by Olli** [comment]
No they are not exactly 500kb. I'd tryed it on 2 different servers. One with not so much memory and one where the PHP process has a lot of memory.
Not all images are grey. Many very large images are correct imported.
There is also nothing special in the logs.

**Comment by Olli** [comment]
Thanks for the hint. I've tryed it and it worked very well. So I assume it's no problem of the import mechanism.
