### ISSUE TITLE
syntax error, unexpected '[' in /plugins/flickr2piwigo/main.inc.php on line 61 

### ISSUE THREAD

**Issue by ethanotoole** [mistic100/Flickr2Piwigo#49]
Piwigo latest version (recent install) and the flickr2piwigo plugin current version.
PHP Version 5.3.3 (CentOS)

    $prefilters[] = [
      'ID' => 'flickr',
      'NAME' => l10n('Imported from Flickr'),
    ];

When I remark over it the issue moves to another file with a similar syntax. 
Php version issue?

**Comment by samwilson** [comment]
Yep, that's due to the short array syntax not being supported by your PHP version. Are you able to upgrade PHP? Version 5.3 went EOL more than 5 years ago.

**Comment by ethanotoole** [comment]
Yea, I didn't realize the VM base OS was that old. I will rebuild it on something more modern and redeploy. 
Much thanks for the info!

**Comment by samwilson** [comment]
Cool. No worries! :)
