### ISSUE TITLE
Piwigo - 2.9.1 Login to Flickr-Account not working

### ISSUE THREAD

**Issue by ClaudiaLev** [mistic100/Flickr2Piwigo#5]
Unfortunately the Login to Flickr with the flickr2piwigo-Plugin is not working.
After pressing the "Anmeldung" (login)-Button, the Piwigo-Gallery is closed and you will be redirected to the Flickr Page.

For this reason the plugin is not working at all.

**Comment by antymat** [comment]
Same here. Flickr has improved their 3'rd party plugin integration mid-July, kipi-plugins are also affected. All the same - it would be nice to be able to move from flickr just for that, and so this plugin would be helpful. 
Any chance of a fix in sight?

**Comment by ceinmart** [comment]
I found this version of phpFlickr , but naturally it isn't compatible with the plug in, need adaptations. 
Unfortunately I don't know PHP to do this... 

https://github.com/DantSu/PHPFlickr-Oauth

http://www.developpeur-web.dantsu.com/fr/cours-tutoriels/flickr/a_authenticate-to-flickr-api-with-oauth-and-phpflickr

**Comment by biffhero** [comment]
ClaudiaLev,
antymat,
ceinmart,

Since this issue has been open for over one month with no response by the author, I'm afraid it is up to us to figure this out.  I don't know PHP very well myself, but maybe we can all work on it together.

Thanks,
Rob

**Comment by samwilson** [comment]
I am working on an update to phpFlickr: https://github.com/samwilson/phpflickr which once I've got working properly with oauth, I'll send a PR here to update this plugin.

**Comment by biffhero** [comment]
@samwilson , 

Did you see the message by mistic100 that he is looking to hand off this repository to someone who uses Piwigo?

**Comment by samwilson** [comment]
Yes I did; I'm not going to put my hand up till I've made further progress on PhpFlickr, but once that's all bedded down I'd be interested in maintaining this if @mistic100 is amenable. I also need to get an ApproximateDates plugin functioning, so we can import Flickr dates correctly. :-)

**Comment by samwilson** [comment]
I've sorted out the basic authentication stuff in PhpFlickr, and am now attempting to update this plugin.

**Comment by samwilson** [comment]
This should now be working in version 1.3.0. Can you try it out and report back?

**Comment by biffhero** [comment]
It now logs in to my Flickr account.  I didn't have to reconfigure anything, it used the API key from when I was using this months ago.  Thank you!

I am seeing other problems with the plugin.  I'll open new problems for them.

**Comment by samwilson** [comment]
Terrific. Glad it's working!

**Comment by ceinmart** [comment]
Hi @samwilson , 
I've reinstalled the plugin using the piwigo admin interface. 
It's show is version 1.3.0.
When I click at "login" raise the error below .
What could be?

> Fatal error: Uncaught OAuth\Common\Http\Exception\TokenResponseException: file_get_contents(https://www.flickr.com/services/oauth/request_token): failed to open stream: no suitable wrapper could be found in /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php:73 Stack trace: #0 /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/OAuth1/Service/AbstractService.php(52): OAuth\Common\Http\Client\StreamClient->retrieveResponse(Object(OAuth\Common\Http\Uri\Uri), '', Array) #1 /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/samwilson/phpflickr/src/PhpFlickr.php(718): OAuth\OAuth1\Service\AbstractService->requestRequestToken() #2 /home/imartins/public_html/fotos/plugins/flickr2piwigo/admin/import.php(60): Samwilson\PhpFlickr\PhpFlickr->getAuthUrl('read', 'https://fotos.i...') #3 /home/imartins/public_html/fotos/plugins/flickr2piwigo/admin.php(19): include('/home/imartins/...') #4 /home/imartins/public_html/f in /home/imartins/public_html/fotos/plugins/flickr2piwigo/vendor/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php on line 73

**Comment by ElliotMcGucken** [comment]
Are there any updates to this?  Has anyone gotten Flickr2Piwigo to work?  Thank you! :)

**Comment by samwilson** [comment]
@ElliotMcGucken yep, it should be working correctly now (at least as far as logging in goes; there are still other bugs).

Could you please open a new issue with any bug you're experiencing? Thanks!

**Comment by ElliotMcGucken** [comment]
Thanks Sam!

I actually have yet to try it! :) I am pricing a colocated server running Centos Linux, where I will be running Piwigo and using Flickr2Piwigo.  I will let you know when I have begun the migration of some of my photos.  Thank you!

Have others been able to successfully transfer photos from flickr to Piwigo recently? 

Thanks!

**Comment by samwilson** [comment]
Yes, it's working at least to some extent! (See the currently open issues.) But I'm actively working on it, and am keen to get it working (I've got a bunch of my and others' photos on Flickr that I want to import). I don't feel like any of the bugs are too hard.

**Comment by ElliotMcGucken** [comment]
Thanks Sam!

I have setup a new server running Centos!

Piwigo and flickr2piwigo are running on it!

I have imported a few images, but I am also getting many errors.

Here is my latest screenshot:

I am running PHP 7.2.

Any approximate advice?

Thanks so much!  I look forward to helping you get it working!

Elliot :)

**Comment by ElliotMcGucken** [comment]
![2018-03-08_11-39-39](https://user-images.githubusercontent.com/34756772/37181211-e319576e-22e0-11e8-93df-79cfeaced722.jpg)
Here is a screenshot!

Some things I've noticed:

1. It says "Selection 190168 elements ready for impotration".  I actually have over 300,000 images total!  Most of those are in albums too!

Here is the site:
http://66.45.225.82/pw/piwigo/

2. Flickr2Piwigo is taking long album titles and chopping them up, so I am getting multiple album titles.

For instance, it takes an album title from flickr which has 85 photos, chops it up, and creates five albums, each which has 85 photos:

http://66.45.225.82/pw/piwigo/

Albums:
**- and Beautiful! Athena! [85]  
- Fit [85]  
- Thin [85]  
- and a Gold 45 Revolver Gun! Short Shorts Denim Daisy Dukes Jeans Shorts! Tall [85]  
- Cowboy Boots [85]  
- Pretty Cowgirl Model Goddess with Cowboy Hat [85]**  

The good news is that it is transferring photos!  Thanks!

**Comment by antymat** [comment]
@samwilson Thanks a lot! This works now, ans I am very happy I do not have to move 1600 photos by hand (finding them first).
Thank you!
