### ISSUE TITLE
Flickr2Piwigo 1.3.0 does not import entire album

### ISSUE THREAD

**Issue by biffhero** [mistic100/Flickr2Piwigo#8]
Administration ->
Plugins ->
Flickr2Piwigo ->
List my albums ->
Auto Upload
(no photos selected, 480 in current set)
-> The whole set 
( All 480 photos are selected )
-> Choose album
-> Begin transfer

Processing (1/20) ... (20/20)

And it is finished importing 20 of them.

**Comment by samwilson** [comment]
Thanks for reporting this (and the others). :-)

It looks like this is the same issue that's being tracked in #4.
