### ISSUE TITLE
Flickr2Piwigo 1.3.0 does not list all albums

### ISSUE THREAD

**Issue by biffhero** [mistic100/Flickr2Piwigo#9]
Administration ->
Plugins ->
Flickr2Piwigo ->
List my albums ->
Auto Upload
(no photos selected, 460 in current set)
-> The whole set
( All 460 photos are selected )

When I go to look in the Album: dropdown, I do not see the flickr_import album that I created the previous time.

I don't know if this should be a separate problem or not, but if I click on "create a new album" and then type in the same name as before, it works.  Shouldn't it fail if I ask it to create an album that already exists?

**Comment by biffhero** [comment]
I didn't notice this until now, but I have three flickr_import albums.  :-)

Thanks,
Rob

**Comment by samwilson** [comment]
Do you mean you've got three `flickr_import` albums on Flickr, or on Piwigo?

This error could be due to the 10 minute cache time. Do you see the missing album if you wait more than 10 minutes?

**Comment by biffhero** [comment]
I have three flickr_import albums on Piwigo.

I have since deleted them all.  I am now using your import-all branch, I'll try again with that one.

**Comment by samwilson** [comment]
Sorry I replied too hastily. Yes, try with that branch! :-) 
--

**Comment by biffhero** [comment]
I just did the same steps.

Administration ->
Plugins ->
Flickr2Piwigo ->
List my albums ->
Auto Upload
(no photos selected, 68 in current set)
-> The whole set
( All 68 photos are selected )

I said to create a new album, and called it flickr_import.

The pagination was set to 20, and it imported 20 photos from  Flickr to the Piwigo album flickr_import.

**Comment by biffhero** [comment]
OK, good news.  It shows my Piwigo album flickr_import, and it puts the next set of 20 images into that album.  The bad news is that it still only brings in 20 of them, even though Piwigo says "all 48 of them selected".

**Comment by samwilson** [comment]
Yes, there seems to be a bug with importing the whole album if it's got more photos than are visible in the first page's grid. #4 is tracking that.

Can you try with the "Import all my pictures" option, and see if that is working? it should create all required albums (or put all in a single album if you want).

**Comment by samwilson** [comment]
Just to confirm: is there a problem with the whole list of album titles (i.e the page before viewing a single album), or is it with listing the contents of a single album?

**Comment by biffhero** [comment]
This is when I choose


Administration
Plugins
Flickr2Piwigo
List my albums
Auto Upload (7779 photos) 
(green checkmark notice: 432 pictures are not displayed because already existing in the database.)
(Select: The whole page, The whole set, None, Invert No photo selected, 68 photos in current set )

So the problem is with the Auto Upload album on Flickr.

**Comment by biffhero** [comment]
"Just to confirm: is there a problem with the whole list of album titles (i.e the page before viewing a single album), or is it with listing the contents of a single album?"

When I click on "List my albums", everything goes correctly.  I get a list of all of my albums, from " Auto Upload (7796 photos) " through " Pictures without album (1648 photos) ".  That works properly.

When I choose the single album "Auto Upload", that is when things aren't working quite right.

**Comment by biffhero** [comment]
"Can you try with the "Import all my pictures" option, and see if that is working? it should create all required albums (or put all in a single album if you want)."

Flickr claims we have 7,892 photos.

When I make the choice to import all, I get the following responses:


    6470 pictures are not displayed because already existing in the database.

Selection
85 elements ready for importation

**Comment by samwilson** [comment]
The "Import all my pictures" option I meant was the one that *doesn't* list all albums, but rather imports all Flickr photos (either into a single album, or into the same album names that are on Flickr).

So I think this issue is the same problem as #4 — but I won't close it just yet. Currently, I'm working on getting the other import process working (import-all; #12) and then will look at the single-album import part of things (which will of course use the same back end, so improvements made for the other will help here too). Shouldn't be too long. Please test the import-all and let me know if that works (of course, if you're trying to only import one album, that's not very useful, sorry!)

**Comment by samwilson** [comment]
A fix for this will be coming soon I hope. Will track the progress in #4.
